Pages/Crud.cshtml.cs
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc;

namespace LogIn.Pages;

public class CrudModel : PageModel
{

    private readonly ILogger<CrudModel> _logger;

    public CrudModel(ILogger<CrudModel> logger)
    {
        _logger = logger;
    }

    public void OnGet()
    {

    }
}
    

Pages/DeleteAccount.cshtml.cs
using LogIn.DataAccess;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace LogIn.Pages;

public class DeleteAccountModel : PageModel
{
    private readonly ILogger<DeleteAccountModel> _logger;
    private readonly DatabaseAccess dataAccess = new DatabaseAccess();

    [BindProperty]
    public string AccountToBeDeletedUsername { get; set; } = string.Empty;
    [BindProperty]
    public string AccountToBeDeletedPassword { get; set; } = string.Empty;

    public DeleteAccountModel(ILogger<DeleteAccountModel> logger)
    {
        _logger = logger;
    }

    public void OnGet()
    {

    }

    public IActionResult OnPost()
    {
        try
        {
            // call 'delete' method
            dataAccess.deleteAccount(AccountToBeDeletedUsername, AccountToBeDeletedPassword);
        }catch(Exception ex)
        {
            Console.WriteLine("Account Could not be deleted");
            Console.WriteLine("[ERROR] - " + ex.ToString());
            return RedirectToPage("/Error");
        }
        return RedirectToPage("/Index");
    }

}

Pages/Error.cshtml.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace LogIn.Pages;

[ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
[IgnoreAntiforgeryToken]
public class ErrorModel : PageModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

    private readonly ILogger<ErrorModel> _logger;

    public ErrorModel(ILogger<ErrorModel> logger)
    {
        _logger = logger;
    }

    public void OnGet()
    {
        RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
    }
}

Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace LogIn.Pages;

public class IndexModel : PageModel
{
    private readonly ILogger<IndexModel> _logger;

    public IndexModel(ILogger<IndexModel> logger)
    {
        _logger = logger;
    }

    public void OnGet()
    {

    }
}

Pages/Read.cshtml.cs
using LogIn.DataAccess;
using LogIn.Model;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace LogIn.Pages;

public class ReadModel : PageModel
{
    private readonly DatabaseAccess dataAccess = new DatabaseAccess();
    public List<string> userList = new List<string>();

    // default constructor
    public ReadModel() { }

    
    // default page controller
    public void OnGet()
    {
        try
        {
            userList = dataAccess.AllUsers();

            // check to see if username exists
            if(userList.Count == 0)
            {
                RedirectToPage("/Error");
            }
        }catch(Exception ex)
        {
            Console.WriteLine("Error in fetching users");
            Console.WriteLine("[ERROR] - " + ex.ToString());
            RedirectToPage("/Error");
        }
    }
}

Pages/Register.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using LogIn.DataAccess;

namespace LogIn.Pages;

public class RegisterModel : PageModel
{

    private readonly ILogger<RegisterModel> _logger;
    private readonly DatabaseAccess dataAccess = new DatabaseAccess();

    [BindProperty]
    public string Email { get; set; } = string.Empty;

    [BindProperty]
    public string Username { get; set; } = string.Empty;

    [BindProperty]
    public string Password { get; set; } = string.Empty;

    public RegisterModel(ILogger<RegisterModel> logger)
    {
        _logger = logger;
    }

    public void OnGet()
    {

    }


    // Create a new Account Route 
    public IActionResult OnPost()
    {
        try
        {
            // call dataaccess 'create' method
            dataAccess.registerUser(Email, Username, Password);
        }catch(Exception ex){
            // log errors
            Console.WriteLine("error in creating new user account..");
            Console.WriteLine("[ERROR] - " + ex.ToString());
            RedirectToPage("/Error");
        }

        // log success
        Console.WriteLine("New user has been created!");

        // return back to index page if everything worked
        return RedirectToPage("/Index");
    }
}

Pages/Search.cshtml.cs
using Microsoft.AspNetCore.Mvc.RazorPages;
using LogIn.DataAccess;
using Microsoft.AspNetCore.Mvc;

namespace LogIn.Pages;

public class SearchModel : PageModel
{

    private readonly DatabaseAccess dataAccess = new DatabaseAccess();
    public List<string> searchResults = new List<string>();
    [BindProperty]
    public string Username { get; set; } = string.Empty;

    

    public void OnGet()
    {

    }

    public void OnPostSearch()
    {
        try
        {
            // check if user input is valid
            if(Username == string.Empty)
            {
                RedirectToPage("/Error");
            }

            // if yes than
            searchResults = dataAccess.searchByUsername(Username);

            // check if the username exists
            if(searchResults == null)
            {
                RedirectToPage("/Error");
            }

        }catch(Exception ex)
        {
            Console.WriteLine("There has been an error searching for user with the username: " + Username);
            Console.WriteLine("[ERROR] - " + ex.ToString());
            RedirectToPage("/Error");
        }

    }
}

Pages/UpdateAccount.cshtml.cs
using LogIn.DataAccess;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace LogIn.Pages;

public class UpdateAccountModel : PageModel
{
    private readonly ILogger<UpdateAccountModel> _logger;
    private readonly DatabaseAccess dataAccess = new DatabaseAccess();

    [BindProperty]
    public string Password { get; set; } = string.Empty;

    [BindProperty]
    public string OldUsername { get; set; } = string.Empty;
    [BindProperty]
    public string OldPassword { get; set; } = string.Empty;

    [BindProperty]
    public string UpdatedUsername { get; set; } = string.Empty;
    [BindProperty]
    public string UpdatedPassword { get; set; } = string.Empty;

    public UpdateAccountModel(ILogger<UpdateAccountModel> logger)
    {
        _logger = logger;
    }

    public void OnGet()
    {

    }

    public IActionResult OnPostUpdateUsername()
    {
        try
        {
            dataAccess.updateUsername(OldUsername, UpdatedUsername, Password);
            // maybe add username here for validation purposes
            //dataAccess.updatePassword(OldPassword, UpdatedPassword);
        }catch(Exception ex)
        {
            Console.WriteLine("Unable to update information..");
            Console.WriteLine("[ERROR] - " + ex.ToString());
        }
        
        return RedirectToPage("/Index");
    }

    public IActionResult OnPostUpdatePassword()
    {
        try
        {
            dataAccess.updatePassword(OldPassword, UpdatedPassword);
        }catch(Exception ex)
        {
            Console.WriteLine("Unable to update Information");
            Console.WriteLine("[ERROR] - " + ex.ToString());
            return RedirectToPage("/Error");
        }
        return RedirectToPage("/Index");
    }
}

Pages/Crud.cshtml
@page
@model CrudModel
@{
    ViewData["Title"] = "Crud Information Page";
}


<h1>CRUD Information Page</h1>
<p>Create Account (CREATE) - <a href="/Register">Register Page</a></p>
<p>All Users (READ) - <a href="/Read">All Users Page</a></p>
<p>Update Account (UPDATE)- <a href="/UpdateAccount">Update Account Page</a></p>
<p>Delete Account (DELETE)- <a href="/DeleteAccount">Delete Account Page</a></p>
<br />
<h3>Other Operations</h3>
<p>User Search (READ) - <a href="/Search">Search Users Page</a></p>

Pages/DeleteAccount.cshtml
@page
@model DeleteAccountModel
@{
    ViewData["Title"] = "Delete Account Page";
}

<h1>DELETE USER ACCOUNT</h1>

<form method="POST">
    <input asp-for="AccountToBeDeletedUsername" placeholder="Enter Username To Delete Account" />
    <input asp-for="AccountToBeDeletedPassword" placeholder="Enter Username To Delete Account" />
    <button type="submit">Delete</button>
</form>

Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}

<div class="links">
    <button><a style="text-decoration:none;" href="/Register">Create Account</a></button>
    <button><a style="text-decoration:none;" href="/Read">All Users</a></button>
    <button><a style="text-decoration:none;" href="/UpdateAccount">Update Account Information</a></button>
    <button><a style="text-decoration:none;" href="/DeleteAccount">Delete Account</a></button>
    <button><a style="text-decoration:none;" href="/Search">User Search</a></button>
</div>

Pages/Read.cshtml
@page
@model ReadModel
@{
    ViewData["Title"] = "Search Users Page";
}

<br />
<h2>Serach for other Users!</h2>

<br />

<table>
    <thread>
        <tr>
            <th><u>All Users</u></th>
        </tr>
    </thread>
    <tbody>
        @foreach(var item in Model.userList)
        {
                <tr>
                    <td>@item</td>
                </tr>
        }
    </tbody>
</table>

Pages/Register.cshtml
@page
@model RegisterModel
@{
    ViewData["Title"] = "Register Page";
}

<div>
    <form method="post">
        <span>Register Form</span>
        <input asp-for="Email" placeholder="EMAIL" />
        <input asp-for="Username" placeholder="USERNAME" />
        <input asp-for="Password" placeholder="PASSWORD" />
        <button class="btn-primary" type="submit">Create Account</button>
    </form>
</div>

Pages/Search.cshtml
@page
@model SearchModel
@{
    ViewData["Title"] = "Search Page";
}

<h1>Search for other Users!</h1>

@if(TempData.ContainsKey("Alert Message"))
 {
    <div class="alert">
        @TempData["AlertMessage"]
    </div>
 }

<form method="POST" asp-page-handler="Search">
    <input placeholder="SEARCH" asp-for="Username" />
    <button type="submit">SEARCH</button>
</form>

<table>
    <thread>
        <tr>
            <th><u>Search Results</u></th>
        </tr>
    </thread>
    <tbody>
        @foreach (var item in Model.searchResults)
        {
            <tr>
                <td style="color:blue">@item</td>
            </tr>
        }
    </tbody>
</table>

Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - LogIn</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/LogIn.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-page="/Index">LogIn</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Index">Home</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - LogIn - <a asp-area="" asp-page="/Crud">CRUD</a>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Pages/UpdateAccount.cshtml
@page
@model UpdateAccountModel
@{
    ViewData["Title"] = "Update Account Page";
}

<form method="POST" asp-page-handler="UpdateUsername">
    <input asp-for="OldUsername" placeholder="Old Username"/>
    <input asp-for="UpdatedUsername" placeholder="New Username"/>
    <p>To Update Username, Enter Your Password.</p>
    <input asp-for="Password" placeholder="Password"/>
    <button type="submit">Change Username</button>
</form>

<h1>------------------------</h1>

<form method="POST" asp-page-handler="UpdatePassword">
    <input asp-for="OldPassword" placeholder="Old Password"/>
    <input asp-for="UpdatedPassword" placeholder="New Password"/>
    <button type="submit">Change Password</button>
</form>